apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: crossplane-provider-aws-admin
rules:
- apiGroups: ["aws.upbound.io"]
  resources: ["providerconfigs", "providerconfigusages"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: provider-aws-ec2-permissions
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: crossplane-provider-aws-admin  # Adjust if using a different role
subjects:
- kind: ServiceAccount
  name: provider-aws-ec2-c339a6b52234
  namespace: crossplane-system

