apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xvpc-basic
  labels:
    provider: example
spec:
  compositeTypeRef:
    apiVersion: network.example.com/v1alpha1
    kind: XVPC
  resources:
    - name: vpc
      base:
        apiVersion: ec2.aws.upbound.io/v1beta1
        kind: VPC
        spec:
          forProvider:
            cidrBlock: 172.16.0.0/16   # default CIDR; can be overridden with patch
            region: us-east-2         # default region; can be overridden with patch
            tags:
              Name: DemoVpc
          providerConfigRef:
            name: default
      patches:
        - fromFieldPath: "spec.cidrBlock"
          toFieldPath: "spec.forProvider.cidrBlock"
        - fromFieldPath: "spec.region"
          toFieldPath: "spec.forProvider.region"

