apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xvpcs.network.example.com
spec:
  group: network.example.com
  names:
    kind: XVPC
    plural: xvpcs
  claimNames:
    kind: XVPCClaim
    plural: xvpcclaims
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                cidrBlock:
                  type: string
                region:
                  type: string

