apiVersion: ec2.aws.upbound.io/v1beta2
kind: Instance
metadata:
  name: ubuntu-instance
spec:
  forProvider:
    region: us-west-2
    ami: ami-075686beab831bb7f
    instanceType: t2.micro
    keyName: example
    subnetId: subnet-0ce51da8e5de3c7c3
    vpcSecurityGroupIdSelector:
       matchLabels:
        testing.upbound.io/example-name: example
    associatePublicIpAddress: true

