apiVersion: ec2.aws.upbound.io/v1beta1
kind: KeyPair
metadata:
  name: example
spec:
  forProvider:
    publicKey: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC1K0t+jdTS8KtOT4c6qMHOr+OgGYrc/kbbi+RCpSQHNTXk+74JCGxDzsVII9mT3oUqaX3Vw/qkJubb6EgFhWciSW+al/hJnOrWaeSD9LZxegggamxoxA+Cea0q++7tvvOEEULlmISLY8+yfa05WpDy8VnHllpwbX2shDJlPB4bTd7v3A37ux+QQlfJqPJP/VjMM+GE+1t3ZluXLdkf3YQUM+fzrn7mca1LXY+0xB5vXZISeLKrGPgFK5dycSXTQgIdnarztXXmEnx4oj2ggYb+wlsuIfwv3mOI+lp/1Dxt2Rb6aeq45nuOdCHedCna991jri/8eh3fqxKqfnl4QZznDvbGnz7as5259VX1tV8otaGnRuLLwQrW9o9Ahd2o3llBltYUYRlPwa2CTl8ZMZ/Eu30ZVi1V+Z2IWqj72cq1NXQm8qjMRmZFEKdMARtdeyIX30CFjg7XEz9/CJgxWTvK8KLbVA81hVz9/Ts7HCbAzj8cxbO7oJI0FKuVD1XSny8= root@ip-172-31-0-132
    region: us-west-2
