apiVersion: ec2.aws.upbound.io/v1beta1
kind: RouteTable
metadata:
  annotations:
    meta.upbound.io/example-id: ec2/v1beta2/route
  labels:
    testing.upbound.io/example-name: table
  name: table
spec:
  forProvider:
    region: us-east-2
    tags:
      Name: example
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example

