apiVersion: ec2.aws.upbound.io/v1beta2
kind: VPCEndpoint
metadata:
  annotations:
    meta.upbound.io/example-id: ec2/v1beta2/vpcendpoint
  labels:
    testing.upbound.io/example-name: ec2
  name: ec2
spec:
  forProvider:
    region: us-west-2
    serviceName: com.amazonaws.us-west-2.ec2
    vpcEndpointType: Interface
    vpcIdRef:
      name: imported-vpc  # Reference to the existing VPC
  providerConfigRef:
    name: default

