apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xvpc.aws.network.example.com
  labels:
    provider: aws
spec:
  compositeTypeRef:
    apiVersion: network.example.com/v1alpha1
    kind: XVPC
  resources:
    - name: vpc
      base:
        apiVersion: ec2.aws.upbound.io/v1beta1
        kind: VPC
        spec:
          forProvider:
            cidrBlock: 10.1.0.0/16
            enableDnsSupport: true
            enableDnsHostNames: true
          providerConfigRef:
            name: default
      patches:
        - fromFieldPath: "spec.cidrBlock"
          toFieldPath: "spec.forProvider.cidrBlock"
        - fromFieldPath: "spec.region"
          toFieldPath: "spec.forProvider.region"

    - name: subnet-a
      base:
        apiVersion: ec2.aws.upbound.io/v1beta1
        kind: Subnet
        spec:
          forProvider:
            cidrBlock: 10.1.1.0/24
            availabilityZone: us-west-2a
            vpcIdSelector:
              matchControllerRef: true
          providerConfigRef:
            name: default
      patches:
        - fromFieldPath: "spec.subnets[0].cidr"
          toFieldPath: "spec.forProvider.cidrBlock"
        - fromFieldPath: "spec.subnets[0].availabilityZone"
          toFieldPath: "spec.forProvider.availabilityZone"
        - fromFieldPath: "spec.region"
          toFieldPath: "spec.forProvider.region"

    - name: vpcendpoint
      base:
        apiVersion: ec2.aws.upbound.io/v1beta2
        kind: VPCEndpoint
        metadata:
          name: ec2
        spec:
          forProvider:
            region: us-west-2
            serviceName: com.amazonaws.us-west-2.ec2
            vpcEndpointType: Interface
            vpcIdSelector:
              matchControllerRef: true
          providerConfigRef:
            name: default
      patches:
        - fromFieldPath: "spec.vpcEndpoint.serviceName"
          toFieldPath: "spec.forProvider.serviceName"
        - fromFieldPath: "spec.vpcEndpoint.vpcEndpointType"
          toFieldPath: "spec.forProvider.vpcEndpointType"
        - fromFieldPath: "spec.region"
          toFieldPath: "spec.forProvider.region"
    - name: vcpSubnetassociation
      base: 
        apiVersion: ec2.aws.upbound.io/v1beta1
        kind: VPCEndpointSubnetAssociation
        metadata:
          name: sn-ec2
        spec:
          forProvider:
            region: us-west-2
            subnetIdSelector:
              matchControllerRef: true
            vpcEndpointIdSelector:
              matchControllerRef: true
