apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: xvpcs.network.example.com
spec:
  group: network.example.com
  names:
    kind: XVPC
    plural: xvpcs
    singular: xvpc
    shortNames:
      - xvc
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                cidrBlock:
                  type: string
                region:
                  type: string
                subnets:
                  type: array
                  items:
                    type: object
                    properties:
                      cidr:
                        type: string
                      availabilityZone:
                        type: string
                vpcEndpoint:
                  type: object
                  properties:
                    serviceName:
                      type: string
                    routeTableIds:
                      type: array
                      items:
                        type: string
                    vpcEndpointType:
                      type: string
                      enum:
                        - Interface
                        - Gateway

